name: Publish package

on: workflow_call

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm ci
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}
      - run: npm run build

  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
      - run: npm install
        env:
          NPM_AUTH_TOKEN: ${{ secrets.GH_REGISTRY_PACKAGES }}
      - run: npm run test

  publish-gpr:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: "@thijmenos"
      - run: npm ci
      - run: npm run build --if-present
      - run: |
          git config user.name "Thijmen Brand"
          git config user.email "thijmen@ik.nu"
          npm version patch
          git push
          git push --tags
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
